mv adsp_loader_dlkm.ko audio_adsp_loader.ko
mv apr_dlkm.ko audio_apr.ko
mv bolero_cdc_dlkm.ko audio_bolero_cdc.ko
mv cpe_lsm_dlkm.ko audio_cpe_lsm.ko
mv hdmi_dlkm.ko audio_hdmi.ko
mv machine_dlkm.ko audio_machine_trinket.ko
mv mbhc_dlkm.ko audio_mbhc.ko
mv native_dlkm.ko audio_native.ko
mv pinctrl_lpi_dlkm.ko audio_pinctrl_lpi.ko
mv pinctrl_wcd_dlkm.ko audio_pinctrl_wcd.ko
mv platform_dlkm.ko audio_platform.ko
mv q6_dlkm.ko audio_q6.ko
mv q6_notifier_dlkm.ko audio_q6_notifier.ko
mv q6_pdr_dlkm.ko audio_q6_pdr.ko
mv rx_macro_dlkm.ko audio_rx_macro.ko
mv snd_event_dlkm.ko audio_snd_event.ko
mv stub_dlkm.ko audio_stub.ko
mv swr_ctrl_dlkm.ko audio_swr_ctrl.ko
mv swr_dlkm.ko audio_swr.ko
mv tx_macro_dlkm.ko audio_tx_macro.ko
mv usf_dlkm.ko audio_usf.ko
mv va_macro_dlkm.ko audio_va_macro.ko
mv wcd934x_dlkm.ko audio_wcd934x.ko
mv wcd9335_dlkm.ko audio_wcd9355.ko
mv wcd937x_dlkm.ko audio_wcd937x.ko
mv wcd937x_slave_dlkm.ko audio_wcd937x_slave.ko
mv wcd9xxx_dlkm.ko audio_wcd9xxx.ko
mv wcd_core_dlkm.ko audio_wcd_core.ko
mv wcd_cpe_dlkm.ko audio_wcd_cpe.ko
mv wcd_spi_dlkm.ko audio_wcd_spi.ko
mv wglink_dlkm.ko audio_wglink.ko
mv wsa881x_dlkm.ko audio_wsa881x.ko
mv wsa_macro_dlkm.ko audio_wsa_macro.ko
